### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by wjd1009** [tianyuanhuang/citypulse#1]
Hello, thank you very much for your sharing. is it convenient to provide the data set of citypulse for download? Why did I only see one form?

**Comment by tianyuanhuang** [comment]
Thank you for your interest! Due to [Google's copyright and privacy policy](https://about.google/brand-resource-center/products-and-services/geo-guidelines/#general-guidelines-copyright-fair-use), we are unable to provide the dataset of imagery. Please refer to the `PanoID` columns in our published CSV file to download the street view images using the [Google Street View Static API](https://developers.google.com/maps/documentation/streetview/overview).
